services:
  ada-triplestore:
    image: ada-ae/virtuoso-opensource:1.0
    build:
      context: ./triplestore
      dockerfile: Dockerfile
      args:
        - ADAAE_UID=${ADAAE_UID:-50000}
        - ADAAE_GID=${ADAAE_GID:-50000}
    env_file:
      - .env
      - secrets.env
      - ada-ae.env
    environment:
      - VIRTUOSO_INI_FILE=/virtuoso.ini
    volumes:
      - virtuoso-db:/database
      - import:/import
    networks:
      ada-ae:
        aliases:
          - internal-ada-triplestore
      ada-rproxy: {}
#    ports:
#      - 8890:8890
#      - 1111:1111
# FIXME: add health check and test for serivce healthy in depends_on of other services
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
#      interval: 5s
#      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "300k"
        max-file: "5"
    restart: always

  ada-explorer:
    image: ada-ae/explorer:1.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - ONTOLOGY_BASE_URI=${ONTOLOGY_BASE_URI:-http://ada.cinepoetics.org}
    env_file:
      - .env
    networks:
      - ada-rproxy
    depends_on:
      - ada-rest-api
    user: "nginx:nginx"
    logging:
      driver: "json-file"
      options:
        max-size: "300k"
        max-file: "5"
    restart: always

  ada-rest-api:
    image: ada-ae/rest-api:1.0
    build:
      context: ./rest_api
      dockerfile: Dockerfile
      args:
        - OPENJDK_VER=${OPENJDK_VER:-14}
        - ADAAE_UID=${ADAAE_UID:-50000}
        - ADAAE_GID=${ADAAE_GID:-50000}
    env_file:
      - .env
      - secrets.env
      - ada-ae.env
    environment:
      - ADVENE_SERVICE_URL=http://advene-service:5002/convertazp
      - RDF_UPLOADER_URL=http://rdf-uploader:5003/uploadrdf
      - FRAME_SERACH_URL=http://reverse-frame-search:5000/query
    networks:
      ada-ae:
        aliases:
          - internal-ada-rest-api
      ada-rest-api:
        aliases:
          - internal-ada-rest-api
      ada-rproxy: {}
#    ports:
#      - 7002:7002
    depends_on:
      - ada-triplestore
      - advene-service
      - rdf-uploader
    logging:
      driver: "json-file"
      options:
        max-size: "300k"
        max-file: "5"
    restart: always
    command: ["http://internal-ada-triplestore:8890/sparql", "http://internal-ada-triplestore:8890/sparql-auth", "/api"]

  advene-service:
    image: ada-ae/advene-service:1.0
    build:
      context: ./advene_service
      dockerfile: Dockerfile
      args:
        - ADAAE_UID=${ADAAE_UID:-50000}
        - ADAAE_GID=${ADAAE_GID:-50000}
    env_file:
      - .env
      - ada-ae.env
    networks:
      - ada-ae
#    ports:
#      - 5002:5002
    logging:
      driver: "json-file"
      options:
        max-size: "300k"
        max-file: "5"
    restart: always

  rdf-uploader:
    image: ada-ae/rdf-uploader:1.0
    build:
      context: ./rdf_uploader
      dockerfile: Dockerfile
      args:
        - ADAAE_UID=${ADAAE_UID:-50000}
        - ADAAE_GID=${ADAAE_GID:-50000}
    env_file:
      - .env
      - secrets.env
      - ada-ae.env
    environment:
      - TRIPLESTORE_HOST=internal-ada-triplestore
      - TRIPLESTORE_PORT=1111
    volumes:
      - import:/import
    networks:
      - ada-ae
#    ports:
#      - 5003:5003
    depends_on:
      - ada-triplestore
    logging:
      driver: "json-file"
      options:
        max-size: "300k"
        max-file: "5"
    restart: always

  lodview:
    image: ada-ae/lodview:1.0
    build:
      context: ./lodview
      dockerfile: Dockerfile
      args:
        # Don't use global OPENJDK_VER. WAR compile does not work with Openjdk 16 or 17!
        - OPENJDK_VER=15
        - TOMCAT_VER=${TOMCAT_VER:-9.0.46}
        - ONTOLOGY_BASE_URI=${ONTOLOGY_BASE_URI:-http://ada.cinepoetics.org}
        - PUBLIC_SPARQL_URL=http://internal-ada-triplestore:8890/sparql
    env_file:
      - .env
      - ada-ae.env
    networks:
      ada-ae: {}
      ada-rproxy: {}
#    ports:
#      - 8080:8080
    depends_on:
      - ada-triplestore
    logging:
      driver: "json-file"
      options:
        max-size: "300k"
        max-file: "5"
    restart: always

  ontoviz:
    image: ada-ae/ontoviz:latest
    build:
      context: ./ontoviz
      dockerfile: Dockerfile
    env_file:
      - ada-ae.env
    networks:
      - ada-ae
      - ada-rproxy
    depends_on:
      - ada-rest-api
    user: "nginx:nginx"
    logging:
      driver: "json-file"
      options:
        max-size: "300k"
        max-file: "5"
    restart: always


volumes:
  import: {}
  
  virtuoso-db:
    name: virtuoso-db
    driver_opts:
      type: none
      device: $HOME/volumes/virtuoso
      o: bind


networks:
  ada-ae:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.10.0/28

  ada-rest-api:
    name: ada-rest-api
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.11.0/27

  ada-rproxy:
     external: true
